language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"
  - "pypy"
services:
  - redis-server
# install dependencies
install:
  - pip install -e .
  - pip install -r requirements-docs.txt
  - pip install -r requirements-pytest.txt
  - pip install codecov
# run tests
script:
  - pytest --cov=./
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then codecov; fi
  - cd docs
  # build the docs on 2.7 and 3.6 (sphinx requires 2.7 or >=3.4)
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then make html; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then make html; fi